# Generated by Django 2.2.7 on 2020-02-29 14:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agravo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(default=None, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Ignorado')], default='I', max_length=25)),
                ('data_nascimento', models.DateField(default=None)),
                ('ocupacao', models.CharField(default=None, max_length=50)),
                ('gestacao', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre'), ('4', 'Idade gestacional ignorada'), ('5', 'Não'), ('6', 'Não se aplica'), ('9', 'Ignorado')], default='9', max_length=25)),
                ('uf', models.CharField(choices=[('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal')], default='PI', max_length=25)),
                ('municipio', models.CharField(default=None, max_length=25)),
                ('cep', models.CharField(default=None, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_primeiros_sintomas', models.DateField(default=None)),
                ('data_notificacao', models.DateField(default=None)),
                ('sinais_clinicos', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Febre'), (2, 'Mialgia'), (3, 'Cefaleia'), (4, 'Exantema'), (5, 'Vomito'), (6, 'Nauseas'), (7, 'Dor Nas Costas'), (8, 'Conjuntivite'), (9, 'Artrite'), (10, 'Artralgia Intensa'), (11, 'Petequias'), (12, 'Leucopenia'), (13, 'Prova do Laço Positiva'), (14, 'Dor Retroorbital')], default=None, max_length=32)),
                ('doencas_pre_existentes', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Diabetes'), (2, 'Doencas Hematologicas'), (3, 'Hepatopatias'), (4, 'Doenca Renal Cronica'), (5, 'Hipertensao Arterial'), (6, 'Doenca Acido Peptica')], default=None, max_length=11)),
                ('evoluido', models.BooleanField(default=False)),
                ('agravo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agravo_notificacao', to='site_mapa.Agravo')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_notificacao', to='site_mapa.Paciente')),
                ('unidade_saude', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unidade_saude', to='site_mapa.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome Completo')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('staff', models.BooleanField(blank=True, default=False)),
                ('admin', models.BooleanField(blank=True, default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='site_mapa.CategoriaProfissional')),
                ('notificacoes', models.ManyToManyField(blank=True, to='site_mapa.Notificacao')),
                ('pacientes', models.ManyToManyField(blank=True, to='site_mapa.Paciente')),
                ('vinculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculo', to='site_mapa.Estabelecimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
