# Generated by Django 2.2.7 on 2020-02-29 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notificacoes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pacientes',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agravo_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
