# Generated by Django 2.2.7 on 2020-03-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0006_auto_20200229_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ubs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_ubs', to='site_mapa.Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Ignorado', 'Ignorado')], default='Ignorado', max_length=25),
        ),
    ]
