# Generated by Django 2.2.7 on 2020-03-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0007_auto_20200310_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='evoluido',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='situacao_atual',
            field=models.CharField(choices=[('Notificado', 'Notificado'), ('Confirmado', 'Confirmado'), ('Alta', 'Alta'), ('Óbito', 'Óbito')], default='Notificado', max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ubs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_ubs', to='site_mapa.Estabelecimento'),
        ),
    ]
