# Generated by Django 2.2.7 on 2020-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0008_auto_20200310_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cns',
            field=models.CharField(default=None, max_length=15, unique=True, verbose_name='CNS'),
        ),
    ]
