# Generated by Django 2.2.7 on 2020-04-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0011_auto_20200403_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_notificacao',
            field=models.DateField(default=None),
        ),
    ]
