# Generated by Django 2.2.12 on 2020-07-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0015_auto_20200403_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='agravo',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='unidade_saude',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ubs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vinculo',
        ),
        migrations.DeleteModel(
            name='Agravo',
        ),
        migrations.DeleteModel(
            name='CategoriaProfissional',
        ),
        migrations.DeleteModel(
            name='Estabelecimento',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
