# Generated by Django 2.2.12 on 2020-07-29 07:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='doencas_pre_existentes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Diabetes'), (2, 'Doencas hematológicas'), (3, 'Hepatopatias'), (4, 'Doença renal crônica'), (5, 'Hipertensão arterial'), (6, 'Doença ácido-péptica'), (7, 'Doenças auto-imunes')], default=None, max_length=13),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sinais_clinicos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Febre'), (2, 'Mialgia'), (3, 'Cefaleia'), (4, 'Exantema'), (5, 'Vômito'), (6, 'Náuseas'), (7, 'Dor nas costas'), (8, 'Conjuntivite'), (9, 'Artrite'), (10, 'Artralgia intensa'), (11, 'Petéquias'), (12, 'Leucopenia'), (13, 'Prova do laço positiva'), (14, 'Dor retroorbital')], default=None, max_length=32),
        ),
    ]
