# Generated by Django 2.2.12 on 2020-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200811_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agravo',
            name='doencas_pre_existentes',
            field=models.ManyToManyField(blank=True, default=None, related_name='agravo_doencas', to='notification.DoencasPreExistentes'),
        ),
        migrations.AlterField(
            model_name='agravo',
            name='sinais_clinicos',
            field=models.ManyToManyField(blank=True, default=None, related_name='agravo_sinais', to='notification.SinaisClinicos'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='doencas_pre_existentes',
            field=models.ManyToManyField(blank=True, default=None, related_name='notificacao_doencas', to='notification.DoencasPreExistentes'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sinais_clinicos',
            field=models.ManyToManyField(blank=True, default=None, related_name='notificacao_sinais', to='notification.SinaisClinicos'),
        ),
    ]
