# Generated by Django 2.2.12 on 2020-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cep',
        ),
        migrations.AddField(
            model_name='paciente',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
